### ISSUE TITLE
Assign Proposals created from surveys to a special user

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#124] opened 2017-02-21 18:07 UTC
#### :tophat: User Story
As an admin. when submitting new proposals from the admin form without any email associated, the proposals appear as "Official Proposal" and it should display "Enquesta / Encuesta".

We should create a fake user with this name and when a proposal is created from a survey that doesn't have an email, assign it to this user.

We also need to migrate the data at production: all proposals that don't have an author should be assigned to this fake user.

#### :clipboard: Related documentation
![imagen](https://cloud.githubusercontent.com/assets/23509895/23176885/337bf43e-f865-11e6-962a-0dea518077c2.png)

#### :dart: Acceptance criteria
Proposals without email data associated are shown as "Enquesta / Encuesta"

#### :pushpin: Related issues

**Comment by lastpotion** [comment] 2017-02-22 08:59
@carolromero before I start working on this can you clarify me a couple of things?

If I make this change means that the platform will never have another way to make ```Propostes officials```, is that correct? Or we want to keep this as an option in some other way?

Cheers!

**Comment by oriolgual** [comment] 2017-02-22 09:22
No @lastpotion that's not correct, we need to keep both options :/

**Comment by mrcasals** [comment] 2017-02-22 09:50
> when submitting new proposals from the admin form without any email associated

@carolromero do you mean the Surveys form in the admin? As I understand, the issue is: when submitting an anonymous survey result from the admin form (that is, without any email address) and adding the related proposals, these proposals appear as Official but should appear as Anonymous, is that right?

@oriolgual right, now, when a proposal does not have a related author it's considered as official, that's why we're facing this issue. This raises a problem: we need to differentiate the anonymous proposals from the official ones in the DB right now. We thought about adding a boolean to set a proposal as official. This would never appear in the UI since it's pointless (those created from the admin proposal form are always official, and those created from the survey result form are never official but can be anonymous). An anonymous proposal would have `author_id: nil, official: false`, an official one would have `author_id: nil, official: true`. Right now, both official and anonymous have the `author_id: nil` and we do not have a way to differentiate them.

We do not have a way to edit a proposal from the admin for transparency sake, but this forbids us to edit the proposals one by one, so we might need to update them from the DB directly in order to have the correct data. We might need a list of the real official proposals, if any, and set the rest as anonymous.

In order to add the boolean field, we need to modify the main `decidim` repo, so this is not just a L'Hospitalet issue. 

My proposed changes are:

1. Go to `decidim` and add the `official` boolean column to proposals and set it to `false by default
1. All proposals created from the Proposals feature in the admin part should be set as `official`
1. Back in L'Hospitalet, update `decidim` once the previous changes are merged.
1. Ensure those anonymous proposals created from the SurveyResult form in the admin are set as `official: false`
1. Set the correct official proposals as `official`, the rest as anonymous

**Comment by oriolgual** [comment] 2017-02-23 07:24
@mrcasals I'm not sure I want to add new flags to proposals, since then we'd either have to move it to the `decidim` repo or keep it in mind for the future. What about we create a user named "Enquesta" or "Proposta d'enquesta" and we assign all the proposals to this user? /cc @carolromero

**Comment by josepjaume** [comment] 2017-02-23 07:28
You could always find_or_create a user with an email like
polls@lhon-participa.com or something.

**Comment by oriolgual** [comment] 2017-02-23 07:30
Yup @josepjaume, that's what I meant.

**Comment by carolromero** [comment] 2017-02-23 07:39
Sonds good @oriolgual
This is an isolatef need for this soecific use case.

**Comment by oriolgual** [comment] 2017-02-23 07:42
@mrcasals @lastpotion issue updated.

**Closed** 2017-02-24 09:07 UTC
Labels: in-progress
