### ISSUE TITLE
Error when uploading images from admin panel

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#75] opened 2017-01-30 09:17 UTC
#### :tophat: User Story
Admin panel crashes when uploading a new banner image for a process.

**Comment by mrcasals** [comment] 2017-01-30 09:24
Checking the error logs, it looks like the image was too big. We have a limit of 10MB for the image, can you try reducing the size?

**Comment by mrcasals** [comment] 2017-01-30 09:24
We'll try to make a better error message for this meanwhile.

**Comment by carolromero** [comment] 2017-01-30 09:26
ok, I'll try with a different one. The image was a bit big but not that heavy (2,2MB). And the admin panel simply goes blank, no error message :)

**Comment by mrcasals** [comment] 2017-01-30 09:27
Hm weird, we'll look into it. Thanks for reporting!

**Comment by mrcasals** [comment] 2017-01-30 09:29
@carolromero can you send us the image that caused the error, so that we can try to reproduce it? You can drag and drop the image in the comments box here and it will be uploaded.

**Comment by carolromero** [comment] 2017-01-30 09:32
@mrcasals I just tried the same image resized and it works. Maybe the problem it's not weight but size?
Anyways I attach here the original.
![nww_-_ol8hy-fano-miasta](https://cloud.githubusercontent.com/assets/23509895/22417999/4ab6081e-e6d7-11e6-807d-37f95f0efe6b.jpg)

**Comment by mrcasals** [comment] 2017-01-30 09:37
Yes, we have a limit of 2000px both in height and width, and this image exceeds that limit. We'll work to fix this, thanks!

**Comment by carolromero** [comment] 2017-01-30 09:41
Yup, a text showing the optimal or recommended image size/weight would be great!

**Comment by oriolgual** [comment] 2017-01-30 10:43
@mrcasals the problem of the app crashing is that the validation is at the model instead of the form, so when saving it at the command we aren't rescuing the error.

**Comment by oriolgual** [comment] 2017-02-02 13:10
Closed by https://github.com/AjuntamentdeBarcelona/decidim/issues/667

**Closed by oriolgual** 2017-02-02 13:10 UTC
Labels: bug
